# Generated by Django 5.1 on 2024-08-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorcd', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('mentorName', models.TextField()),
                ('mentoremail', models.EmailField(max_length=254)),
            ],
        ),
    ]
